#!/usr/bin/env python3
"""Build Watson's E2E fixture repo: one issue/PR set per use case.

Creates (if missing) the PRIVATE repo delltrak/watson-e2e-lab from e2e/lab/, then
the scenarios below. Idempotent: progress is kept in e2e/.lab-state.json, so a
rerun only builds what is missing. GitHub writes go ONLY to the lab repo.

Needs: gh (logged in with repo scope) and git. Usage: python3 e2e/lab_setup.py
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = 'delltrak/watson-e2e-lab'
HERE = Path(__file__).resolve().parent
TEMPLATE = HERE / 'lab'
STATE = HERE / '.lab-state.json'
CLONE = HERE / '.lab-clone'


def run(cmd, cwd=None, check=True):
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if check and result.returncode:
        sys.exit(f'failed: {" ".join(cmd)}\n{result.stderr.strip()}')
    return result.stdout.strip()


def gh(*args, check=True):
    return run(['gh', *args], check=check)


def git(*args, check=True):
    return run(['git', *args], cwd=CLONE, check=check)


def load():
    return json.loads(STATE.read_text()) if STATE.exists() else {}


def save(state):
    STATE.write_text(json.dumps(state, indent=2) + '\n')


def ensure_repo():
    if subprocess.run(['gh', 'repo', 'view', REPO], capture_output=True).returncode:
        gh('repo', 'create', REPO, '--private',
           '--description', 'Watson E2E fixtures (generated by watson-triage/e2e; not for real work)')
    if not (CLONE / '.git').exists():
        run(['gh', 'repo', 'clone', REPO, str(CLONE)])
    if not git('ls-remote', '--heads', 'origin', 'main', check=False):
        shutil.copytree(TEMPLATE, CLONE, dirs_exist_ok=True)
        git('checkout', '-B', 'main')
        git('add', '-A')
        git('commit', '-m', 'Lab app with tests and CI')
        git('push', '-u', 'origin', 'main')
    git('checkout', 'main')
    git('pull', '--ff-only', 'origin', 'main')


def number_of(url):
    return int(url.strip().rstrip('/').rsplit('/', 1)[1])


def issue(title, body):
    return number_of(gh('issue', 'create', '-R', REPO, '--title', title, '--body', body))


def pull(branch, title, body, files, draft=False):
    git('checkout', 'main')
    git('pull', '--ff-only', 'origin', 'main')
    git('checkout', '-B', branch)
    for path, content in files.items():
        target = CLONE / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
    git('add', '-A')
    git('commit', '-m', title)
    git('push', '-f', '-u', 'origin', branch)
    args = ['pr', 'create', '-R', REPO, '--base', 'main', '--head', branch, '--title', title, '--body', body]
    number = number_of(gh(*args, *(['--draft'] if draft else [])))
    git('checkout', 'main')
    return number


def head_sha(pr):
    return gh('pr', 'view', str(pr), '-R', REPO, '--json', 'headRefOid', '--jq', '.headRefOid')


def verdict(pr, text):
    sha = head_sha(pr)
    gh('pr', 'comment', str(pr), '-R', REPO, '--body', f'Revisão independente — commit `{sha[:7]}`\n\n{text}')


def merge(pr):
    gh('pr', 'merge', str(pr), '-R', REPO, '--squash', '--delete-branch')
    for _ in range(30):
        data = json.loads(gh('pr', 'view', str(pr), '-R', REPO, '--json', 'state,mergeCommit'))
        if data['state'] == 'MERGED' and data.get('mergeCommit'):
            git('checkout', 'main')
            git('pull', '--ff-only', 'origin', 'main')
            return data['mergeCommit']['oid']
        time.sleep(2)
    sys.exit(f'PR #{pr} did not merge')


def wait_ci(sha, timeout=600):
    deadline = time.time() + timeout
    while time.time() < deadline:
        runs = json.loads(gh('api', f'repos/{REPO}/actions/runs?head_sha={sha}',
                             '--jq', '[.workflow_runs[] | {status, conclusion}]'))
        if runs and all(r['status'] == 'completed' for r in runs):
            return [r['conclusion'] for r in runs]
        time.sleep(10)
    sys.exit(f'CI on {sha[:7]} did not finish in time')


def note(slug, text):
    return {f'docs/notes/{slug}.md': text + '\n'}


CUSTOMERS = '''"""Customer registration."""
from app.cpf import is_valid


class InvalidCPF(ValueError):
    pass


def register(db, name, cpf):
    """Save a customer; an invalid CPF is refused and nothing is saved."""
    if not is_valid(cpf):
        raise InvalidCPF('CPF inválido')
    db[cpf] = name
    return cpf
'''
CUSTOMERS_TESTS = '''import unittest

from app.customers import InvalidCPF, register


class RegisterTests(unittest.TestCase):
    def test_valid_cpf_is_saved(self):
        db = {}
        register(db, 'Ana', '529.982.247-25')
        self.assertEqual(db, {'529.982.247-25': 'Ana'})

    def test_invalid_cpf_is_refused_and_not_saved(self):
        db = {}
        with self.assertRaisesRegex(InvalidCPF, 'CPF inválido'):
            register(db, 'Ana', '529.982.247-26')
        self.assertEqual(db, {})
'''
COUPONS = '''"""Checkout coupons."""


class ExpiredCoupon(ValueError):
    pass


def redeem(code, expires_on, today):
    """The coupon code, or ExpiredCoupon after its expiry date."""
    if today > expires_on:
        raise ExpiredCoupon('Coupon expired')
    return code
'''
COUPONS_TESTS = '''import unittest
from datetime import date

from app.coupons import ExpiredCoupon, redeem


class RedeemTests(unittest.TestCase):
    def test_valid_until_expiry(self):
        self.assertEqual(redeem('SAVE10', date(2026, 9, 30), date(2026, 9, 30)), 'SAVE10')

    def test_expired_is_rejected(self):
        with self.assertRaisesRegex(ExpiredCoupon, 'Coupon expired'):
            redeem('SAVE10', date(2026, 9, 30), date(2026, 10, 1))
'''


# ---------------------------------------------------------------- scenarios ----
def s01_refs_merged(state):
    """Merged PR says Refs #N, delivers exactly what the issue asks, trusted APROVAR verdict → suggest_close."""
    n = issue('Cadastro de clientes aceita CPF inválido',
              'Não existe validação de CPF no cadastro: qualquer número é salvo.\n\n'
              'Critério: criar app/customers.py com register(db, name, cpf) que recusa CPF inválido '
              '(dígitos verificadores, via app.cpf.is_valid) com a mensagem "CPF inválido" e não salva nada; '
              'CPF válido é salvo. Com testes.')
    pr = pull('e2e/s01-customers', 'Cadastro de clientes recusa CPF inválido',
              f'## Issue\n\nRefs #{n}\n\nregister() valida o CPF com app.cpf.is_valid antes de salvar.',
              {'app/customers.py': CUSTOMERS, 'tests/test_customers.py': CUSTOMERS_TESTS})
    verdict(pr, '**Veredito: APROVAR.**')
    return {'issue': n, 'pr': pr, 'merge': merge(pr)}


def s02_closes_reopened(state):
    """Merged PR says Closes #N; the issue was reopened after the merge → review_close."""
    n = issue('Desconto acima de 100% gera preço negativo',
              'Aplicar desconto de 120% no checkout gera preço negativo.')
    pr = pull('e2e/s02-discount-guard', 'Recusar desconto fora de 0 a 100',
              f'Closes #{n}\n\nA função apply já recusa percentuais fora do intervalo.',
              note('s02-discount', 'app.discount.apply recusa percentuais fora de 0-100.'))
    sha = merge(pr)
    for _ in range(30):
        if gh('issue', 'view', str(n), '-R', REPO, '--json', 'state', '--jq', '.state') == 'CLOSED':
            break
        time.sleep(2)
    time.sleep(2)
    gh('issue', 'reopen', str(n), '-R', REPO)
    return {'issue': n, 'pr': pr, 'merge': sha}


def s03_pr_open(state):
    """A trusted draft PR is still open → pr_open (never a duplicate draft)."""
    n = issue('Mostrar subtotal por item no carrinho', 'Cada linha do carrinho deve mostrar preço x quantidade.')
    pr = pull('e2e/s03-subtotal', 'Subtotal por item (em andamento)', f'Refs #{n}\n\nPrimeira versão.',
              note('s03-subtotal', 'Rascunho do subtotal por item.'), draft=True)
    return {'issue': n, 'pr': pr}


def s04_umbrella(state):
    """Umbrella issue cited by a multi-issue merged PR → merged_partial, no lead line."""
    umbrella = issue('Épico: melhorias do carrinho',
                     'Acompanhar as melhorias do carrinho:\n\n- subtotal por item\n- cupons\n- frete')
    helper = issue('Aceitar cupom de desconto no carrinho', 'Permitir informar um cupom no carrinho.')
    pr = pull('e2e/s04-coupons', 'Cupons no carrinho (parte 1)', f'Refs #{umbrella}\nRefs #{helper}',
              note('s04-coupons', 'Primeira parte dos cupons.'))
    return {'issue': umbrella, 'helper': helper, 'pr': pr, 'merge': merge(pr)}


def s05_negated(state):
    """A merged PR mentions #N saying it does not close it → none."""
    n = issue('Exportar pedidos em CSV', 'O time financeiro precisa exportar os pedidos do mês em CSV.')
    other = state['s04_umbrella']['helper']
    pr = pull('e2e/s05-export-prep', 'Preparação para exportação',
              f'Refs #{other}\n\nRelacionado a #{n}, sem encerrá-la: a exportação vem depois.',
              note('s05-export', 'Estrutura preparada para exportação futura.'))
    return {'issue': n, 'pr': pr, 'merge': merge(pr)}


def s06_unchecked(state):
    """Merged PR with Refs, but the issue checklist still has an unchecked item → review_close."""
    n = issue('Frete grátis acima de R$ 200',
              'Pedidos acima de R$ 200 têm frete grátis.\n\nCritérios:\n- [x] Regra no backend\n'
              '- [ ] Aviso na tela do carrinho')
    pr = pull('e2e/s06-free-shipping', 'Frete grátis acima de R$ 200 (backend)', f'Refs #{n}',
              note('s06-shipping', 'Regra de frete grátis no backend.'))
    return {'issue': n, 'pr': pr, 'merge': merge(pr)}


def s07_later_pr(state):
    """A later multi-issue merged PR also cites #N without closing it → review_close."""
    n = issue('Histórico de pedidos do cliente', 'O cliente deve ver os pedidos anteriores.')
    helper = issue('Paginação da lista de pedidos', 'A lista de pedidos precisa de paginação.')
    first = pull('e2e/s07-history', 'Histórico de pedidos', f'Refs #{n}',
                 note('s07-history', 'Tela de histórico de pedidos.'))
    first_merge = merge(first)
    time.sleep(2)
    later = pull('e2e/s07-history-pages', 'Histórico com paginação', f'Refs #{n}\nRefs #{helper}',
                 note('s07-history-pages', 'Paginação no histórico.'))
    return {'issue': n, 'helper': helper, 'pr': first, 'later_pr': later, 'merge': first_merge,
            'later_merge': merge(later)}


def s08_ci_failed(state):
    """Merged PR with Refs whose merge commit fails CI → review_close; main is fixed afterwards."""
    n = issue('Arredondar desconto para baixo', 'O desconto deveria arredondar para baixo, não para o mais próximo.')
    broken = ('"""Price discounts."""\n\n\ndef apply(price, percent):\n'
              '    """Price after a percentage discount (0-100)."""\n'
              '    return round(price * (100 - percent) / 100 - 1, 2)\n')
    pr = pull('e2e/s08-discount-rounding', 'Arredondamento do desconto', f'Refs #{n}',
              {'app/discount.py': broken})
    sha = merge(pr)
    conclusions = wait_ci(sha)
    # Restore main so the other scenarios keep a green default branch.
    shutil.copy(TEMPLATE / 'app' / 'discount.py', CLONE / 'app' / 'discount.py')
    git('add', '-A')
    git('commit', '-m', 'Restore discount.apply (lab fixture reset)')
    git('push', 'origin', 'main')
    return {'issue': n, 'pr': pr, 'merge': sha, 'merge_ci': conclusions}


def s09_closed(state):
    """Closed issue → no suggestion."""
    n = issue('Trocar ícone do carrinho', 'Usar o ícone novo do design system.')
    gh('issue', 'close', str(n), '-R', REPO, '--reason', 'completed')
    return {'issue': n}


def s11_bug_no_pr(state):
    """Real bug in app/cart.py, no PR yet (auto-draft candidate later)."""
    n = issue('Total do carrinho ignora a quantidade',
              'Com 2 unidades de um produto de R$ 10,00 o total aparece R$ 10,00. Deveria ser R$ 20,00.\n\n'
              'Passos: adicionar o mesmo produto duas vezes (quantidade 2) e ver o total.\n\n'
              'Esperado: total = preço x quantidade para cada item.')
    return {'issue': n}


def s12_needs_info(state):
    """Vague report → needs_info, no lead."""
    return {'issue': issue('Não funciona', 'Deu erro aqui, arruma por favor.')}


def s13_en_refs_merged(state):
    """English issue, merged PR with Refs that delivers the fix, APPROVED verdict → suggest_close in English."""
    n = issue('Checkout accepts expired coupon codes',
              'There is no expiry check: expired coupon codes are still applied.\n\n'
              'Acceptance: add app/coupons.py with redeem(code, expires_on, today) that rejects a coupon after '
              'its expiry date with the message "Coupon expired" and accepts it up to that date. With tests.')
    pr = pull('e2e/s13-coupons', 'Reject expired coupons at checkout', f'Refs #{n}\n\nredeem() checks the expiry date.',
              {'app/coupons.py': COUPONS, 'tests/test_coupons.py': COUPONS_TESTS})
    verdict(pr, '**Verdict: APPROVED.**')
    return {'issue': n, 'pr': pr, 'merge': merge(pr)}


SCENARIOS = [s01_refs_merged, s02_closes_reopened, s03_pr_open, s04_umbrella, s05_negated, s06_unchecked,
             s07_later_pr, s08_ci_failed, s09_closed, s11_bug_no_pr, s12_needs_info, s13_en_refs_merged]


def main():
    ensure_repo()
    state = load()
    state['repo'] = REPO
    for build in SCENARIOS:
        if build.__name__ in state:
            continue
        print(f'building {build.__name__} ...', flush=True)
        state[build.__name__] = build(state)
        save(state)
    main_sha = git('rev-parse', 'HEAD')
    state['main_ci'] = wait_ci(main_sha)
    save(state)
    print(json.dumps(state, indent=2))


if __name__ == '__main__':
    main()
